name = "PulseFormal"
version = "0.1.0"
defaultTargets = ["PulseFormal", "pulse_ir", "pulse_traces"]

[[lean_lib]]
name = "PulseFormal"

[[lean_exe]]
name = "pulse_ir"
root = "CompilerMain"

[[lean_exe]]
name = "pulse_traces"
root = "TraceMain"
